### PR TITLE
change Client interface to accept AccountAddress instead of hex encoded string address

### PR DESCRIPTION
**Pull request by xli**

### CODE REVIEW

**Comment by thefallentree** [comment]
why do we need this change?  AccountAddress is a libra type, I am not sure we should be depending on it on the API level, hex looks prefect good for me.

**Comment by xli** [comment]
> why do we need this change? AccountAddress is a libra type, I am not sure we should be depending on it on the API level, hex looks prefect good for me.

AccountAddress is used everywhere except this Client API.
It is more consistent to use one type instead of two.
I don't think we can avoid AccountAddress, it only matters whether you have bytes array type (which is the AccountAddress), or string type.

**Comment by thefallentree** [comment]
The problem I had when working on pylibra2 is that the client API doesn't return AccountAddress in the response objects,  it is all hex string,  so when using data in an api response to make another calls we are forcing user to convert them from hex string to AccountAddress, do you see the same problem in golang sdk?

**Comment by xli** [comment]
> The problem I had when working on pylibra2 is that the client API doesn't return AccountAddress in the response objects, it is all hex string, so when using data in an api response to make another calls we are forcing user to convert them from hex string to AccountAddress, do you see the same problem in golang sdk?

It is better to have one consistent AccountAddress type across all APIs. 
I'm not sure how the response data is used here, ideally, as API has no idea where the string is from, we should do data validation. Hence internally will need try convert string address to AccountAddress.

If the use you mentioned is more in test code, then I don't think we should optimize for it.

**Review by thefallentree — APPROVED** [review]

**Pull request merged**
